python run_classifier.py \
  --do_lower_case=true \
  --do_train=false \
  --do_eval=false \
  --do_predict=true \
  --save_for_serving=true \
  --vocab_file=/home/u4839782/bert-multi-gpu/models/bert_pretrained/chinese_wwm_L-12_H-768_A-12/vocab.txt \
  --bert_config_file=/home/u4839782/bert-multi-gpu/models/bert_pretrained/chinese_wwm_L-12_H-768_A-12/bert_config.json \
  --max_seq_length=512 \
  --use_gpu=true \
  --num_gpu_cores=1 \
  --task_name=classification_2 \
  --init_checkpoint=/home/u4839782/bert-multi-gpu/models/news_paragraph_classification_2 \
  --data_dir=/home/u4839782/bert-multi-gpu/data/news_paragraph_classification_2/0824_paragraph/ \
  --output_dir=/home/u4839782/bert-multi-gpu/test_output/news_paragraph_classification_2/0824_paragraph/
